baseURL = '/'
languageCode = 'en-us'
title = 'RSA Blog'
theme = 'not-much'

[markup]
  [markup.highlight]
    noClasses = false
    style = "github-dark"

[[menu.main]]
identifier = "github"
name = "github"
title = "GitHub"
url = "https://github.com/RSA-Internal/rsa-blog"
weight = 3

[[menu.main]]
identifier = "tags"
name = "tags"
title = "tags"
url = "/tags"
weight = 2
